#! /bin/sh
bspc rule -r "*"

nm-applet &
xrdb ~/.Xresources &
feh --bg-scale --no-fehbg ~/Imágenes/Wallpapers/arch.png &
~/.config/polybar/launch.sh

bspc monitor eDP1 -d 1 2 3
bspc monitor HDMI1 -d 4 5 6 7 8 9 0

bspc config click_to_focus none
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config top_padding		 0
bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
